services:
  service1:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - mode: ingress
        target: 3000
        published: 3000
    environment:
      - MEME_API_URL=https://api.imgflip.com/get_memes
